#define GL_SILENCE_DEPRECATION
#ifdef __APPLE__
#include <GLUT/glut.h>
#else
#include <GL/glut.h>
#endif
#include <cmath>
#define PI M_PI
#define FULL_TURN 2.0f*PI
#define QUARTER_TURN FULL_TURN/4.0f

const int SUN_SEGMENTS = 32;
GLfloat sunVertices[(SUN_SEGMENTS + 2) * 2];

void drawCircle(float x, float y, float radius, GLfloat *arr) {
  const int segments = SUN_SEGMENTS;

  arr[0] = x;
  arr[1] = y;

  for (int i = 0; i <= segments; i++) {
    float angle = (float)i / segments * FULL_TURN + QUARTER_TURN;
    int offset = (i + 1) * 2;
    arr[offset] = x + radius * cosf(angle);
    arr[offset + 1] = y + radius * sinf(angle);
  }
}

GLfloat mountainVertices[] = {
  -0.85f, -0.65f,
  -0.35f,  0.15f,
   0.10f, -0.65f,
   0.45f,  0.05f,
   0.85f, -0.65f,
};

GLfloat groundVertices[] = {
  -0.95f, -0.65f,
   0.95f, -0.65f,
   0.95f, -0.95f,
  -0.95f, -0.95f,
};

void display() {
  glClear(GL_COLOR_BUFFER_BIT);

  // Sun: generated by the reusable drawCircle helper.
  drawCircle(0.55f, 0.55f, 0.23f, sunVertices);
  glColor3ub(255, 190, 30);
  glEnableClientState(GL_VERTEX_ARRAY);
  glVertexPointer(2, GL_FLOAT, 0, sunVertices);
  glDrawArrays(GL_TRIANGLE_FAN, 0, SUN_SEGMENTS + 2);
  glDisableClientState(GL_VERTEX_ARRAY);

  // Mountain: one vertex array and one draw call.
  glColor3ub(139, 75, 35);
  glEnableClientState(GL_VERTEX_ARRAY);
  glVertexPointer(2, GL_FLOAT, 0, mountainVertices);
  glDrawArrays(GL_TRIANGLE_STRIP, 0, 5);
  glDisableClientState(GL_VERTEX_ARRAY);

  // Ground: a plain array-based rectangle.
  glColor3ub(60, 160, 70);
  glEnableClientState(GL_VERTEX_ARRAY);
  glVertexPointer(2, GL_FLOAT, 0, groundVertices);
  glDrawArrays(GL_QUADS, 0, 4);
  glDisableClientState(GL_VERTEX_ARRAY);

  glFlush();
}

int main(int argc, char **argv) {
  glutInit(&argc, argv);
  glutInitWindowSize(600, 600);
  glutCreateWindow("PE_15 - Fully Array-Based Scene");
  glutDisplayFunc(display);
  glutMainLoop();
  return 0;
}
